"""V_00_24_change in invoice_id field

Revision ID: 1e52bfbd9103
Revises: f5f643ea36ff
Create Date: 2023-11-07 12:52:53.615337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e52bfbd9103"
down_revision: Union[str, None] = "f5f643ea36ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invoice",
        "invoice_id",
        existing_type=sa.INTEGER(),
        type_=sa.SMALLINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invoice",
        "invoice_id",
        existing_type=sa.SMALLINT(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
