"""V_00_15_change in invoice_id field

Revision ID: 3cd3f58fd078
Revises: ba6888cbcb27
Create Date: 2023-11-07 11:21:43.702286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3cd3f58fd078"
down_revision: Union[str, None] = "ba6888cbcb27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
