"""V_00_13_create Invoice table

Revision ID: 4e9c71e0e846
Revises: 9e90d30038a8
Create Date: 2023-11-07 11:05:06.292461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e9c71e0e846"
down_revision: Union[str, None] = "9e90d30038a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=True),
        sa.Column("order_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invoice_id"),
    )
    op.create_index(op.f("ix_invoice_id"), "invoice", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoice_id"), table_name="invoice")
    op.drop_table("invoice")
    # ### end Alembic commands ###
