"""V_00_7_create cart table

Revision ID: 503c1900673c
Revises: 667e77d7fc5d
Create Date: 2023-10-29 13:28:26.872995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "503c1900673c"
down_revision: Union[str, None] = "667e77d7fc5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
