"""V_00_21_change in invoice_id field

Revision ID: 519e91268a92
Revises: 25f697d45375
Create Date: 2023-11-07 12:29:00.829987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "519e91268a92"
down_revision: Union[str, None] = "25f697d45375"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("invoice_invoice_id_key", "invoice", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("invoice_invoice_id_key", "invoice", ["invoice_id"])
    # ### end Alembic commands ###
