"""V_00_11_add status column in order table

Revision ID: 53d46431fac8
Revises: 64a214d16755
Create Date: 2023-11-04 10:17:28.908052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "53d46431fac8"
down_revision: Union[str, None] = "64a214d16755"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("status", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "status")
    # ### end Alembic commands ###
