"""remove stockinvetory column from product table

Revision ID: 99a14ef20c53
Revises: a0c03a7c8c91
Create Date: 2023-12-07 17:37:01.778995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a14ef20c53'
down_revision: Union[str, None] = 'a0c03a7c8c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'stockquantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('stockquantity', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
