"""V_00_17_change in invoice_id field

Revision ID: a0e6bda11482
Revises: 2ba7f7dc460c
Create Date: 2023-11-07 11:32:37.666358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a0e6bda11482"
down_revision: Union[str, None] = "2ba7f7dc460c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
