"""V_00_5_create email_otp table

Revision ID: ad76846bd194
Revises: d8f5d11365ba
Create Date: 2023-10-26 10:28:18.046715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad76846bd194"
down_revision: Union[str, None] = "d8f5d11365ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emailotp",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("userid", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("otp", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["userid"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_emailotp_id"), "emailotp", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_emailotp_id"), table_name="emailotp")
    op.drop_table("emailotp")
    # ### end Alembic commands ###
