"""V_00_13_change in invoice_id field

Revision ID: ba6888cbcb27
Revises: 4e9c71e0e846
Create Date: 2023-11-07 11:17:25.349414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba6888cbcb27"
down_revision: Union[str, None] = "4e9c71e0e846"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("invoice", "invoice_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint("invoice_invoice_id_key", "invoice", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("invoice_invoice_id_key", "invoice", ["invoice_id"])
    op.alter_column("invoice", "invoice_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
