"""V_00_19_change in invoice_id field

Revision ID: d52b2e7db9fd
Revises: e4a1b8c77c87
Create Date: 2023-11-07 12:00:21.206605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d52b2e7db9fd"
down_revision: Union[str, None] = "e4a1b8c77c87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invoice",
        "invoice_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    op.drop_index("ix_invoice_invoice_id", table_name="invoice")
    op.create_index(
        op.f("ix_invoice_invoice_id"), "invoice", ["invoice_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoice_invoice_id"), table_name="invoice")
    op.create_index("ix_invoice_invoice_id", "invoice", ["invoice_id"], unique=False)
    op.alter_column(
        "invoice",
        "invoice_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True,
    )
    # ### end Alembic commands ###
