"""V_00_25_update invoice table

Revision ID: d67305f9480f
Revises: 1e52bfbd9103
Create Date: 2023-11-07 14:21:54.038923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67305f9480f'
down_revision: Union[str, None] = '1e52bfbd9103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoice_invoice_id_key', 'invoice', type_='unique')
    op.drop_column('invoice', 'invoice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('invoice_id', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.create_unique_constraint('invoice_invoice_id_key', 'invoice', ['invoice_id'])
    # ### end Alembic commands ###
