"""v_00_31_add_address_id_in_order_table

Revision ID: d8e209fa0a30
Revises: eca0edeef84c
Create Date: 2024-03-02 16:49:07.861617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e209fa0a30'
down_revision: Union[str, None] = 'eca0edeef84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('address_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'order', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'address_id')
    # ### end Alembic commands ###
