"""V_00_4_remove unique=true from email

Revision ID: d8f5d11365ba
Revises: f3bc57267e44
Create Date: 2023-10-25 23:17:30.035632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8f5d11365ba"
down_revision: Union[str, None] = "f3bc57267e44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_email_key", "user", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("user_email_key", "user", ["email"])
    # ### end Alembic commands ###
