"""V_00_18_change in invoice_id field

Revision ID: e4a1b8c77c87
Revises: a0e6bda11482
Create Date: 2023-11-07 11:55:11.835247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4a1b8c77c87"
down_revision: Union[str, None] = "a0e6bda11482"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
