"""V_00_3_add otp column

Revision ID: f3bc57267e44
Revises: d412d066af92
Create Date: 2023-10-25 17:44:36.680737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3bc57267e44"
down_revision: Union[str, None] = "d412d066af92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("otp", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "otp")
    # ### end Alembic commands ###
