"""V_00_23_change in invoice_id field

Revision ID: f5f643ea36ff
Revises: fa13153aa2f6
Create Date: 2023-11-07 12:30:55.619075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5f643ea36ff"
down_revision: Union[str, None] = "fa13153aa2f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "invoice", ["invoice_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "invoice", type_="unique")
    # ### end Alembic commands ###
