"""V_00_22_change in invoice_id field

Revision ID: fa13153aa2f6
Revises: 519e91268a92
Create Date: 2023-11-07 12:30:01.199177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa13153aa2f6'
down_revision: Union[str, None] = '519e91268a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
